clang-tidy: delete default constructor
Default constructor was invalid for class semantics and caused
clang-tidy/Clang diagnostics. Mark the default constructor as
`=delete` to prevent accidental default construction and keep
-Werror builds green. No functional changes.

Fixed below errors
'''
../attn/pel/stream.hpp:55:13: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
   55 |     Stream& operator=(const Stream&) = default;
../analyzer/service_data.hpp:41:18: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
   41 |     ServiceData& operator=(const ServiceData&) = default;
'''

Change-Id: Iac8c99e8bc58b79aca2995a9188956e12b23fd2a
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>