meson: Add phosphor-logging dependency where required
Address issues such as

```
FAILED: attn/libattn_lib.a.p/attn_monitor.cpp.o
ccache c++ -Iattn/libattn_lib.a.p -Iattn -I../attn -I. -I.. -I../subprojects/sdbusplus/include -I/usr/local/include -I/usr/include -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c++23 -O0 -g -fPIC -DBOOST_ALL_NO_LIB -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_ASIO_DISABLE_THREADS -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -MD -MQ attn/libattn_lib.a.p/attn_monitor.cpp.o -MF attn/libattn_lib.a.p/attn_monitor.cpp.o.d -o attn/libattn_lib.a.p/attn_monitor.cpp.o -c ../attn/attn_monitor.cpp
In file included from ../attn/attn_monitor.cpp:3:
../util/trace.hpp:6:10: fatal error: phosphor-logging/lg2.hpp: No such file or directory
    6 | #include <phosphor-logging/lg2.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Change-Id: Ic73fef3c50cee1c6156df10d9b2d516041ba3a64
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>